using CandidatePortal.Api.Configuration;
using CandidatePortal.Api.Data;
using CandidatePortal.Api.Infrastructure;
using CandidatePortal.Api.Models;
using CandidatePortal.Api.Security;
using Microsoft.EntityFrameworkCore;

namespace CandidatePortal.Api.Services;

public sealed class DatabaseBootstrapper(
    PortalDbContext database,
    PortalOptions options,
    PasswordHasher passwordHasher)
{
    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        if (options.AutoCreateSchema)
        {
            await database.Database.EnsureCreatedAsync(cancellationToken);
        }
        await EnsureSchemaEvolutionAsync(cancellationToken);

        if (options.SeedDemoData)
        {
            await SeedDemoDataAsync(cancellationToken);
        }
        await BootstrapAdministratorAsync(cancellationToken);
    }

    private async Task EnsureSchemaEvolutionAsync(CancellationToken cancellationToken)
    {
        if (database.Database.IsSqlServer())
        {
            await database.Database.ExecuteSqlRawAsync(
                "IF COL_LENGTH('jobs', 'expires_at') IS NULL ALTER TABLE jobs ADD expires_at datetime2 NULL;",
                cancellationToken);
            await database.Database.ExecuteSqlRawAsync(
                """
                IF OBJECT_ID(N'audit_logs', N'U') IS NULL
                BEGIN
                    CREATE TABLE audit_logs (
                        id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_audit_logs PRIMARY KEY,
                        admin_user_id int NOT NULL,
                        action nvarchar(50) NOT NULL,
                        entity_type nvarchar(80) NOT NULL,
                        entity_id nvarchar(100) NULL,
                        details nvarchar(max) NOT NULL,
                        created_at datetime2 NOT NULL,
                        CONSTRAINT FK_audit_logs_users_admin_user_id
                            FOREIGN KEY (admin_user_id) REFERENCES users(id) ON DELETE NO ACTION
                    );
                    CREATE INDEX IX_audit_logs_admin_user_id ON audit_logs(admin_user_id);
                    CREATE INDEX IX_audit_logs_created_at ON audit_logs(created_at);
                END
                """,
                cancellationToken);
            return;
        }

        await database.Database.ExecuteSqlRawAsync(
            "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone NULL;",
            cancellationToken);
        await database.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS audit_logs (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                admin_user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                action character varying(50) NOT NULL,
                entity_type character varying(80) NOT NULL,
                entity_id character varying(100) NULL,
                details text NOT NULL,
                created_at timestamp without time zone NOT NULL
            );
            """,
            cancellationToken);
        await database.Database.ExecuteSqlRawAsync(
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_admin_user_id ON audit_logs(admin_user_id);",
            cancellationToken);
        await database.Database.ExecuteSqlRawAsync(
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON audit_logs(created_at);",
            cancellationToken);
    }

    private async Task BootstrapAdministratorAsync(CancellationToken cancellationToken)
    {
        if (options.BootstrapAdminEmail.Length == 0 && options.BootstrapAdminPassword.Length == 0)
        {
            return;
        }
        if (options.BootstrapAdminEmail.Length == 0 || options.BootstrapAdminPassword.Length == 0)
        {
            throw new InvalidOperationException("BOOTSTRAP_ADMIN_EMAIL and BOOTSTRAP_ADMIN_PASSWORD must be provided together");
        }
        if (options.BootstrapAdminPassword.Length < 12)
        {
            throw new InvalidOperationException("BOOTSTRAP_ADMIN_PASSWORD must contain at least 12 characters");
        }

        var existing = await database.Users.SingleOrDefaultAsync(
            user => user.Email == options.BootstrapAdminEmail, cancellationToken);
        if (existing is not null)
        {
            if (existing.Role != "admin")
            {
                throw new InvalidOperationException("The bootstrap administrator email already belongs to a non-admin account");
            }
            return;
        }

        var administrator = new User
        {
            Email = options.BootstrapAdminEmail,
            PasswordHash = passwordHasher.Hash(options.BootstrapAdminPassword),
            FirstName = "Staging",
            LastName = "Administrator",
            CountryCode = "+966",
            Phone = "",
            Country = "Saudi Arabia",
            City = "Riyadh",
            Title = "PBICareerPosting Administrator",
            About = "PBICareerPosting administrator account.",
            Role = "admin",
        };
        administrator.Preferences = new UserPreference();
        database.Users.Add(administrator);
        await database.SaveChangesAsync(cancellationToken);
    }

    private async Task SeedDemoDataAsync(CancellationToken cancellationToken)
    {
        var now = PortalClock.UtcNow();
        if (!await database.Jobs.AnyAsync(cancellationToken))
        {
            var jobs = new[]
            {
                ("Senior React Developer", "IT Division", "Saudi Arabia", "Riyadh", "Engineering", "Senior", true),
                ("Business Analyst", "Business Division", "Saudi Arabia", "Jeddah", "Business Analysis", "Mid-level", true),
                ("UI/UX Designer", "Marketing Division", "Remote", "Remote", "Design", "Mid-level", true),
                ("Project Manager", "Transformation Office", "Saudi Arabia", "Riyadh", "Project Management", "Senior", false),
                ("Data Analyst", "Strategy Division", "Saudi Arabia", "Dammam", "Data & Analytics", "Mid-level", false),
                ("Python API Engineer", "IT Division", "United Arab Emirates", "Dubai", "Engineering", "Mid-level", true),
                ("Talent Acquisition Partner", "People Division", "Saudi Arabia", "Riyadh", "Human Resources", "Mid-level", false),
                ("Cybersecurity Specialist", "IT Division", "Saudi Arabia", "Jeddah", "Information Security", "Senior", true),
                ("Finance Operations Lead", "Finance Division", "Bahrain", "Manama", "Finance", "Senior", false),
                ("Graduate Software Engineer", "IT Division", "Saudi Arabia", "Riyadh", "Engineering", "Entry level", true),
                ("Customer Experience Manager", "Commercial Division", "Kuwait", "Kuwait City", "Customer Experience", "Senior", false),
                ("Supply Chain Planner", "Operations Division", "Saudi Arabia", "Dammam", "Operations", "Mid-level", false),
            };
            for (var index = 0; index < jobs.Length; index++)
            {
                var value = jobs[index];
                database.Jobs.Add(new Job
                {
                    Title = value.Item1,
                    Division = value.Item2,
                    Country = value.Item3,
                    City = value.Item4,
                    JobFunction = value.Item5,
                    CareerLevel = value.Item6,
                    EmploymentType = index == 2 ? "Remote" : "Full-time",
                    Summary = $"Join our team as a {value.Item1}.",
                    Description = $"We are looking for a {value.Item1} to join our growing {value.Item2}.",
                    Requirements = "Relevant experience\nStrong communication and collaboration skills",
                    IsFeatured = value.Item7,
                    PostedAt = now.AddDays(-index),
                    ExpiresAt = now.AddDays(30 - index).Date,
                });
            }
        }

        var candidate = await database.Users.SingleOrDefaultAsync(
            user => user.Email == "john.doe@example.com", cancellationToken);
        if (candidate is null)
        {
            candidate = new User
            {
                Email = "john.doe@example.com",
                PasswordHash = passwordHasher.Hash("Candidate@123"),
                FirstName = "John",
                LastName = "Doe",
                CountryCode = "+966",
                Phone = "55 123 4567",
                Country = "Saudi Arabia",
                City = "Riyadh",
                Title = "Full Stack Developer",
                About = "Passionate developer building reliable web applications.",
                Role = "candidate",
                Preferences = new UserPreference(),
            };
            database.Users.Add(candidate);
        }

        var administrator = await database.Users.SingleOrDefaultAsync(
            user => user.Email == "admin@candidateportal.local", cancellationToken);
        if (administrator is null)
        {
            administrator = new User
            {
                Email = "admin@candidateportal.local",
                PasswordHash = passwordHasher.Hash("Admin@123"),
                FirstName = "Portal",
                LastName = "Administrator",
                CountryCode = "+966",
                Country = "Saudi Arabia",
                City = "Riyadh",
                Title = "PBICareerPosting Administrator",
                About = "PBICareerPosting administrator account.",
                Role = "admin",
                Preferences = new UserPreference(),
            };
            database.Users.Add(administrator);
        }
        await database.SaveChangesAsync(cancellationToken);

        foreach (var user in new[] { candidate, administrator })
        {
            if (!await database.UserPreferences.AnyAsync(
                    preference => preference.UserId == user.Id, cancellationToken))
            {
                database.UserPreferences.Add(new UserPreference { UserId = user.Id });
            }
        }

        if (!await database.Applications.AnyAsync(
                application => application.UserId == candidate.Id, cancellationToken))
        {
            var jobs = await database.Jobs.OrderBy(job => job.Id).Take(3).ToListAsync(cancellationToken);
            var statuses = new[] { "Under Review", "Interview", "Shortlisted" };
            for (var index = 0; index < jobs.Count; index++)
            {
                database.Applications.Add(new Application
                {
                    UserId = candidate.Id,
                    JobId = jobs[index].Id,
                    Status = statuses[index],
                    AppliedAt = jobs[index].PostedAt.AddHours(6),
                });
            }
        }

        if (!await database.Notifications.AnyAsync(
                notification => notification.UserId == candidate.Id, cancellationToken))
        {
            database.Notifications.AddRange(
                new Notification
                {
                    UserId = candidate.Id,
                    Kind = "application",
                    Title = "Interview stage update",
                    Message = "Your Business Analyst application has moved to the interview stage.",
                    Link = "/applications",
                    CreatedAt = now.AddHours(-2),
                },
                new Notification
                {
                    UserId = candidate.Id,
                    Kind = "application",
                    Title = "Application received",
                    Message = "We received your application for Senior React Developer.",
                    Link = "/applications",
                    CreatedAt = now.AddDays(-1),
                },
                new Notification
                {
                    UserId = candidate.Id,
                    Kind = "job",
                    Title = "New roles match your profile",
                    Message = "New engineering opportunities are available in Riyadh.",
                    Link = "/jobs",
                    CreatedAt = now.AddDays(-2),
                });
        }

        await database.SaveChangesAsync(cancellationToken);
    }
}
